Basic verion of footer with layout added
MaPaJBY/phone_catalog_project pull request #10
Opened 2024-05-21 09:30 UTC by bartKarb

I just added first version of footer - some adjustmenst might be needed

2024-05-21 10:02 UTC, JustinNowoczek requested changes

2024-05-21 10:02 UTC, JustinNowoczek commented on src/App.tsx
> +    <Footer />
the footer should be in the layout component

2024-05-21 10:02 UTC, JustinNowoczek commented on src/components/Footer/Footer.tsx
> +import './Footer.scss';
you are not using scss modules

2024-05-21 15:06 UTC, JustinNowoczek requested changes
2 things to correct, everything else looks good

2024-05-21 15:06 UTC, JustinNowoczek commented on src/components/Layout/Layout.tsx
> +      {<Footer />}
why are you using braces

2024-05-21 15:06 UTC, JustinNowoczek commented on public/icons/logo.png
still add images .icons when there is alr a file and icon component

2024-05-23 08:07 UTC, bartKarb commented on public/icons/logo.png
I just corrected mentioned things

2024-05-23 09:01 UTC, bartKarb commented on public/icons/logo.png
I set up formatting for mobile for now. It works well, however refactoring into desktop in future is needed.

2024-05-27 15:11 UTC, closed without merging