Feature/not found page
MaPaJBY/phone_catalog_project pull request #15
Opened 2024-05-21 12:17 UTC by pawelkloc

2024-05-21 12:19 UTC, YarynaPuhach approved these changes

2024-05-21 12:25 UTC, YarynaPuhach commented on src/App.tsx
why /components/NotFoundPage/NotFoundPage';
if we have index.ts, shouldnt it be possible to use simply (/components/NotFoundPage';)

2024-05-21 15:10 UTC, JustinNowoczek requested changes
you need to add whatever folder ".history" is to your gitignore

2024-05-21 15:10 UTC, JustinNowoczek commented on src/components/NotFoundPage/page-not-found.png
we already have this image in src

2024-05-22 12:22 UTC, TideTwo requested changes
You are adding files, like the Cart item, on the branch "not found page" they are not related, please remove those changes from the branch

2024-05-23 10:08 UTC, closed without merging