Feautre/footer2
MaPaJBY/phone_catalog_project pull request #47
Opened 2024-05-24 15:25 UTC by marinatea

https://app.clickup.com/t/8694d8gvw

[UI]: Footer adaptive layout

2024-05-27 05:49 UTC, JustinNowoczek requested changes
The desktop size footer should not stretch any more, and be centered.

2024-05-27 13:35 UTC, JustinNowoczek requested changes

2024-05-27 13:35 UTC, TideTwo commented on public/icons/footer_button.png
This is in icons

2024-05-28 10:54 UTC, marinatea commented on public/icons/footer_button.png
if i replace the button with the one you say, it will not be highlighted when hovering. since it is just a picture with a frame. this footer_button.png does not make any sense as for me

2024-05-29 09:05 UTC, pawelkloc commented
Looks and works good for me ;)

2024-05-29 09:07 UTC, pawelkloc approved these changes

2024-05-29 12:12 UTC, merged